// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartifyWebsite.Models;

#nullable disable

namespace SmartifyWebsite.Migrations
{
    [DbContext(typeof(SmartifyDbContext))]
    [Migration("20250103171916_SeedDummyProductData")]
    partial class SeedDummyProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartifyWebsite.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description_EN")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Description_ES")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Description_TR")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keywords_EN")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Keywords_ES")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Keywords_TR")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name_ES")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name_TR")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProductPhotoPath1")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2671),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "WebApp Pro",
                            Name_ES = "WebApp Pro",
                            Name_TR = "WebApp Pro",
                            Price = 199.99m,
                            ProductCode = "WA-001",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2679),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "WebApp Basic",
                            Name_ES = "WebApp Basic",
                            Name_TR = "WebApp Basic",
                            Price = 99.99m,
                            ProductCode = "WA-002",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2682),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "WebApp Advanced",
                            Name_ES = "WebApp Advanced",
                            Name_TR = "WebApp Advanced",
                            Price = 299.99m,
                            ProductCode = "WA-003",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2685),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "WebApp Pro Plus",
                            Name_ES = "WebApp Pro Plus",
                            Name_TR = "WebApp Pro Plus",
                            Price = 249.99m,
                            ProductCode = "WA-004",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 1,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2687),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "WebApp Starter",
                            Name_ES = "WebApp Starter",
                            Name_TR = "WebApp Starter",
                            Price = 49.99m,
                            ProductCode = "WA-005",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2689),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "DeskApp Pro",
                            Name_ES = "DeskApp Pro",
                            Name_TR = "DeskApp Pro",
                            Price = 159.99m,
                            ProductCode = "DA-001",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2691),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "DeskApp Basic",
                            Name_ES = "DeskApp Basic",
                            Name_TR = "DeskApp Basic",
                            Price = 79.99m,
                            ProductCode = "DA-002",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2693),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "DeskApp Advanced",
                            Name_ES = "DeskApp Advanced",
                            Name_TR = "DeskApp Advanced",
                            Price = 259.99m,
                            ProductCode = "DA-003",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2694),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "DeskApp Pro Plus",
                            Name_ES = "DeskApp Pro Plus",
                            Name_TR = "DeskApp Pro Plus",
                            Price = 209.99m,
                            ProductCode = "DA-004",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 10,
                            CategoryID = 2,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2696),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "DeskApp Starter",
                            Name_ES = "DeskApp Starter",
                            Name_TR = "DeskApp Starter",
                            Price = 59.99m,
                            ProductCode = "DA-005",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 11,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2699),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "MobileApp Basic",
                            Name_ES = "Aplicación Móvil Básica",
                            Name_TR = "Mobil Uygulama Başlangıç",
                            Price = 59.99m,
                            ProductCode = "MA-001",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 12,
                            CategoryID = 3,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2701),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "MobileApp Pro",
                            Name_ES = "Aplicación Móvil Pro",
                            Name_TR = "Mobil Uygulama Pro",
                            Price = 159.99m,
                            ProductCode = "MA-002",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 13,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2703),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "Website for Advocates",
                            Name_ES = "Website for Advocates",
                            Name_TR = "Avukatlar İçin Websitesi",
                            Price = 59.99m,
                            ProductCode = "WD-001",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 14,
                            CategoryID = 4,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2705),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "Website for Doctors",
                            Name_ES = "Website for Doctors",
                            Name_TR = "Doktorlar İçin Websitesi",
                            Price = 159.99m,
                            ProductCode = "WD-002",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 15,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2707),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "Website for Natural Product Shop",
                            Name_ES = "Website for Natural Product Sellers",
                            Name_TR = "Doğal Ürün Satıcıları İçin Websitesi",
                            Price = 59.99m,
                            ProductCode = "EC-001",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 16,
                            CategoryID = 5,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2709),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "Website for Beauty Shop",
                            Name_ES = "Website for Beauty Shop",
                            Name_TR = "Güzellik Ürünleri İçin Websitesi",
                            Price = 159.99m,
                            ProductCode = "EC-002",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 17,
                            CategoryID = 6,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2712),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "Kanban Card Excel Template",
                            Name_ES = "Kanban Card Excel Template",
                            Name_TR = "Kanban Kart Excel Şablonu",
                            Price = 19.99m,
                            ProductCode = "BI-001",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        },
                        new
                        {
                            Id = 18,
                            CategoryID = 6,
                            CreatedDate = new DateTime(2025, 1, 3, 17, 19, 15, 132, DateTimeKind.Utc).AddTicks(2717),
                            Description_EN = "some desc here",
                            Description_ES = "some desc here",
                            Description_TR = "some desc here",
                            IsActive = true,
                            Keywords_EN = "some keywords here",
                            Keywords_ES = "some keywords here",
                            Keywords_TR = "some keywords here",
                            Name_EN = "Monthly Budget Excel Template",
                            Name_ES = "Monthly Budget Excel Template",
                            Name_TR = "Aylık Bütçe Excel Şablonu",
                            Price = 19.99m,
                            ProductCode = "BI-002",
                            ProductPhotoPath1 = "~/images/products/defaultProductImage.jpeg"
                        });
                });

            modelBuilder.Entity("SmartifyWebsite.Data.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName_EN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryName_ES")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryName_TR")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName_EN = "Web Applications",
                            CategoryName_ES = "Aplicaciones Web",
                            CategoryName_TR = "Web Uygulamaları"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName_EN = "Desktop Applications",
                            CategoryName_ES = "Aplicaciones de Escritorio",
                            CategoryName_TR = "Masaüstü Uygulamaları"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName_EN = "Mobile Applications",
                            CategoryName_ES = "Aplicaciones de Móviles",
                            CategoryName_TR = "Mobil Uygulamalar"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName_EN = "Web Design",
                            CategoryName_ES = "Diseño Web",
                            CategoryName_TR = "Web Tasarım"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName_EN = "E Commerce",
                            CategoryName_ES = "Comercio Electrónico",
                            CategoryName_TR = "E Ticaret"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName_EN = "BI and Reporting",
                            CategoryName_ES = "BI y Reportes",
                            CategoryName_TR = "İş Zekası ve Raporlama"
                        });
                });

            modelBuilder.Entity("SmartifyWebsite.Data.Product", b =>
                {
                    b.HasOne("SmartifyWebsite.Data.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartifyWebsite.Data.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
